# General info
name:             Data Science Lab - CETINIA - URJC
highlighter:      rouge

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata

# Server
host:             0.0.0.0
port:             4002
url:              http://www.datasciencelab.es
encoding:         UTF-8

#Build settings
theme:            minima

# Custom variables
license:          CC-BY-SA 4.0
my_theme:    The Project
my_theme_by:      HtmlCoder
my_theme_by_url:  http://htmlcoder.me/
my_theme_url:     https://wrapbootstrap.com/theme/the-project-multipurpose-template-WB0F82581

website:          https://www.datasciencelab.es
blog:             https://www.datasciencelab.es/blog
twitter:          https://twitter.com/URJCDScLab
twitter_user:     URJCDScLab
github_org:       URJCDataScience
